### PR TITLE
Added few more APIs

### PR DESCRIPTION
**Pull request by Priyanshu1035**
Added few more APIs as per the issue  #249 

I have added the GfG,code360 and Mocha.

There are many more apis to add.

## Summary by CodeRabbit

- **New Features**
	- Expanded educational resources with the addition of "GfG" and "code360" for articles and practice questions.
	- Introduced the "Mocha" testing framework to enhance testing capabilities.

These updates enrich the available learning and testing tools for users.

### CODE REVIEW

**Comment by Priyanshu1035** [comment]
Hoping it is good now

**Comment by Priyanshu1035** [comment]
Kindly review the PR if anything is wrong notify me I am new to open source
contribution.

**Review by devvsakib — CHANGES_REQUESTED** [review]
PR is not correct. You have added tools and libraries.  There are 3 categories right now, Learning, Tool, and Career. API should be a new category!

**Comment by Priyanshu1035** [comment]
Can you clarify like what will the API category contain and other possible details?

**Comment by devvsakib** [comment]
Take a pull from main branch, I have added API category

**Pull request closed without merging**
